import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, BarChart3, Building2, Check, Cpu, Network, Search, Server, Users, Wind } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import StructuredData from '@/components/StructuredData';

const services = [
  { no:'01', icon:Users, title:'Strategic talent partnerships', text:'Long-term hiring support for businesses with repeat, project-based or multi-role needs.', points:['Dedicated search capacity','Structured delivery rhythm','Priority market access','Consistent employer story'] },
  { no:'02', icon:Search, title:'Specialist search & shortlist', text:'Targeted outreach for technical, engineering and project professionals who are difficult to reach.', points:['Passive candidate engagement','Technical qualification','Curated shortlists','Interview intelligence'] },
  { no:'03', icon:BarChart3, title:'Market mapping & intelligence', text:'Evidence before action—giving leaders a clear view of skills, salary, availability and competition.', points:['Competitor talent mapping','Salary benchmarking','Location analysis','Skill-gap insight'] },
  { no:'04', icon:Network, title:'Executive & leadership search', text:'Discreet search for the leaders responsible for growth, delivery and technical direction.', points:['Regional leadership','Project directors','Technical executives','Department heads'] },
];
const markets = [
  {icon:Wind,title:'Renewable energy',tag:'Transition',items:['Wind—onshore & offshore','Solar and storage','Hydrogen','Grid and power delivery']},
  {icon:Building2,title:'Engineering & infrastructure',tag:'Delivery',items:['MEP and building services','Civil and structural','Automation and controls','Major programmes']},
  {icon:Server,title:'Mission critical',tag:'Resilience',items:['Data centres','Commissioning and QA/QC','Electrical infrastructure','Cooling and controls']},
  {icon:Cpu,title:'Energy technology',tag:'Innovation',items:['Electrification','Energy software','Smart systems','Climate technology']},
];

export default function Services(){return <main className="overflow-hidden bg-white text-[#03104b]"><Navigation activePage="services"/>
  <section className="watercolor relative pb-24 pt-36 lg:pb-32 lg:pt-44"><div className="brand-grid absolute inset-0 opacity-35"/><div className="section-shell relative grid gap-12 lg:grid-cols-[1fr_.46fr] lg:items-end"><div><p className="eyebrow">How we solve</p><h1 className="mt-8 max-w-5xl text-6xl font-semibold leading-[.91] tracking-[-.065em] sm:text-8xl">Search with purpose.<br/><span className="display-serif text-[#0b4ee8]">Talent with impact.</span></h1></div><div className="border-l border-[#b8ccec] pl-6"><p className="text-lg leading-8 text-slate-600">Four focused services for companies whose hiring challenges cannot be solved by database search alone.</p><Link href="/contact" className="magnetic-link mt-7">Discuss your challenge <ArrowRight className="h-4 w-4"/></Link></div></div></section>

  <section className="-mt-8 px-3 sm:px-5 lg:-mt-12"><div className="relative mx-auto grid max-w-[1500px] gap-2 overflow-hidden rounded-[2rem] bg-[#06165b] p-2 md:grid-cols-2 lg:rounded-[2.75rem]"><div className="relative h-[380px] overflow-hidden rounded-[1.55rem] lg:h-[520px]"><Image src="/renewable-energy-leaders.webp" alt="Renewable energy leaders reviewing a project site" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover"/></div><div className="relative h-[380px] overflow-hidden rounded-[1.55rem] lg:h-[520px]"><Image src="/mission-critical-leaders.webp" alt="Data centre leaders assessing mission-critical systems" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover"/></div><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#020d3b]/55 via-transparent to-transparent"/><div className="absolute bottom-8 left-8 right-8 text-white sm:bottom-12 sm:left-12"><p className="max-w-xl text-2xl font-semibold tracking-[-.03em] sm:text-3xl">From the energy transition to the infrastructure that keeps the world moving.</p></div></div></section>

  <section className="py-24 lg:py-32"><div className="section-shell"><div className="grid gap-5 lg:grid-cols-2">{services.map(({no,icon:Icon,title,text,points},index)=><article key={title} className={`group relative overflow-hidden rounded-[2rem] p-7 sm:p-10 ${index===0?'bg-[#06165b] text-white':'brand-card'}`}><div className="brand-grid absolute inset-0 opacity-[.14]"/><div className="relative flex items-start justify-between"><span className={`font-mono text-xs ${index===0?'text-[#42e5dd]':'text-[#0b4ee8]'}`}>/{no}</span><div className={`grid h-12 w-12 place-items-center rounded-2xl ${index===0?'bg-white/10 text-[#42e5dd]':'bg-[#e7f2ff] text-[#0b4ee8]'}`}><Icon className="h-5 w-5"/></div></div><div className="relative"><h2 className="mt-14 max-w-lg text-4xl font-semibold tracking-[-.045em]">{title}</h2><p className={`mt-5 max-w-xl leading-7 ${index===0?'text-blue-100/70':'text-slate-600'}`}>{text}</p><div className={`mt-10 grid gap-3 border-t pt-7 sm:grid-cols-2 ${index===0?'border-white/15':'border-[#dbe8f8]'}`}>{points.map(point=><div key={point} className="flex items-center gap-2 text-sm font-medium"><span className={`grid h-5 w-5 place-items-center rounded-full ${index===0?'bg-[#20ddd5] text-[#03104b]':'bg-[#dffbf9] text-[#067c79]'}`}><Check className="h-3 w-3"/></span>{point}</div>)}</div>{index===0?<Link href="/partner" className="relative mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#42e5dd]">Apply to partner <ArrowRight className="h-4 w-4"/></Link>:null}</div></article>)}</div></div></section>

  <section className="bg-[#f2f8ff] py-24 lg:py-32"><div className="section-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Market specialisms</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.05em]">Deep context where <span className="display-serif text-[#0b4ee8]">complexity</span> lives.</h2><p className="mt-6 leading-7 text-slate-600">We understand the project environments, technical interfaces and commercial realities behind the job title.</p></div><div className="space-y-3">{markets.map(({icon:Icon,title,tag,items},i)=><div key={title} className="brand-card grid gap-5 p-6 sm:grid-cols-[60px_1fr_1.15fr] sm:items-center"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e5f1ff] text-[#0b4ee8]"><Icon className="h-5 w-5"/></div><div><span className="font-mono text-[10px] text-[#7182a1]">0{i+1} / {tag}</span><h3 className="mt-2 text-xl font-semibold">{title}</h3></div><div className="grid grid-cols-2 gap-3 text-sm text-slate-600">{items.map(item=><p key={item}>{item}</p>)}</div></div>)}</div></div></section>

  <section className="relative overflow-hidden bg-[#06165b] py-24 text-white"><div className="brand-grid absolute inset-0 opacity-20"/><div className="section-shell relative grid gap-12 lg:grid-cols-2"><div><p className="eyebrow !text-[#42e5dd]">Our operating principle</p><h2 className="mt-6 text-5xl font-semibold leading-none tracking-[-.05em] sm:text-6xl">No black box.<br/><span className="display-serif text-[#42e5dd]">Just clarity.</span></h2></div><div className="grid gap-3 sm:grid-cols-2">{[['01','Brief','Define the outcome, context and non-negotiables.'],['02','Map','Build the evidence-led view of the market.'],['03','Engage','Tell a compelling story to carefully selected people.'],['04','Deliver','Qualify deeply and communicate without delay.']].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/15 bg-white/[.06] p-6"><span className="font-mono text-xs text-[#42e5dd]">/{n}</span><h3 className="mt-8 text-xl font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-blue-100/65">{d}</p></div>)}</div></div></section>
  <section className="watercolor px-5 py-20 lg:py-24"><div className="section-shell flex flex-col justify-between gap-9 lg:flex-row lg:items-end"><div><p className="eyebrow">A better search starts with a better brief</p><h2 className="mt-5 max-w-3xl text-5xl font-semibold tracking-[-.05em] sm:text-6xl">Bring us the role that keeps getting <span className="display-serif text-[#0b4ee8]">stuck.</span></h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/partner" className="button-primary shrink-0">Apply to partner <ArrowUpRight className="h-4 w-4"/></Link><Link href="/contact" className="button-outline shrink-0">Start a conversation <ArrowUpRight className="h-4 w-4"/></Link></div></div></section>
  <Footer/><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:'Specialist recruitment services',provider:{'@type':'Organization',name:'Rectify International'},serviceType:services.map(s=>s.title)}}/>
</main>}
