'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, Loader2, Mail, MapPin, Phone, Send } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { toast } from 'sonner';

export default function Contact(){
 const [loading,setLoading]=useState(false); const [data,setData]=useState({name:'',email:'',company:'',phone:'',service:'',message:''});
 const update=(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setData({...data,[e.target.name]:e.target.value});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{const response=await fetch('/api/send-enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to send enquiry');toast.success('Message received',{description:'We will be in touch within one working day.'});setData({name:'',email:'',company:'',phone:'',service:'',message:''});}catch(error){toast.error('Message not sent',{description:error instanceof Error?error.message:'Please email us directly.'});}finally{setLoading(false)}};
 const field='mt-2 w-full rounded-xl border border-[#cfdef2] bg-[#f8fbff] px-4 py-3.5 text-[#03104b] outline-none transition placeholder:text-slate-400 focus:border-[#0b4ee8] focus:bg-white focus:ring-4 focus:ring-[#dceaff]';
 return <main className="overflow-hidden bg-white text-[#03104b]"><Navigation activePage="contact"/>
  <section className="watercolor relative pb-24 pt-36 lg:pb-28 lg:pt-44"><div className="brand-grid absolute inset-0 opacity-35"/><div className="section-shell relative grid gap-12 lg:grid-cols-[1fr_.42fr] lg:items-end"><div><p className="eyebrow">Open a conversation</p><h1 className="mt-8 max-w-5xl text-6xl font-semibold leading-[.91] tracking-[-.065em] sm:text-8xl">Let’s solve what is <span className="display-serif text-[#0b4ee8]">hard to hire.</span></h1></div><p className="border-l border-[#b8ccec] pl-6 text-lg leading-8 text-slate-600">Share the role, team or market challenge. We will respond with a point of view—not a sales script.</p></div></section>
  <section className="py-20 lg:py-28"><div className="section-shell grid gap-7 lg:grid-cols-[.55fr_1fr]">
    <aside className="flex flex-col gap-5"><div className="relative overflow-hidden rounded-[2rem] bg-[#06165b] p-8 text-white sm:p-10"><div className="brand-grid absolute inset-0 opacity-20"/><div className="relative"><p className="eyebrow !text-[#42e5dd]">What happens next</p><ol className="mt-10 space-y-7">{['We review your brief personally','We reply within one working day','We recommend the right search approach'].map((item,i)=><li key={item} className="flex gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-[#42e5dd]/40 font-mono text-[10px] text-[#42e5dd]">0{i+1}</span><span className="pt-1 text-sm leading-6 text-blue-100/80">{item}</span></li>)}</ol></div></div><div className="brand-card p-8 sm:p-10"><p className="eyebrow">Direct contact</p><a href="mailto:info@rectifyinternational.com" className="mt-8 flex items-center gap-3 font-semibold hover:text-[#0b4ee8]"><Mail className="h-5 w-5 text-[#0b4ee8]"/>info@rectifyinternational.com</a><a href="tel:+447399836007" className="mt-5 flex items-center gap-3 font-semibold hover:text-[#0b4ee8]"><Phone className="h-5 w-5 text-[#0b4ee8]"/>+44 7399 836 007</a><div className="mt-7 flex items-center gap-3 border-t border-[#e2ecf8] pt-6 text-sm text-slate-600"><MapPin className="h-5 w-5 text-[#0b4ee8]"/>Germany · UK · Global</div></div></aside>
    <div className="brand-card p-6 sm:p-10 lg:p-12"><div className="flex items-start justify-between gap-6"><div><p className="eyebrow">Your brief</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Tell us where it is stuck.</h2></div><span className="hidden rounded-full bg-[#dffbf9] px-3 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#067c79] sm:block">Confidential</span></div><form onSubmit={submit} className="mt-10 space-y-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Name *<input className={field} name="name" value={data.name} onChange={update} required placeholder="Your name"/></label><label className="text-sm font-semibold">Work email *<input className={field} type="email" name="email" value={data.email} onChange={update} required placeholder="you@company.com"/></label><label className="text-sm font-semibold">Company<input className={field} name="company" value={data.company} onChange={update} placeholder="Organisation"/></label><label className="text-sm font-semibold">Phone<input className={field} name="phone" value={data.phone} onChange={update} placeholder="Optional"/></label></div><label className="block text-sm font-semibold">What support do you need?<select className={field} name="service" value={data.service} onChange={update}><option value="">Select an area</option><option>Specialist search</option><option>Strategic talent partnership</option><option>Executive search</option><option>Market mapping</option><option>Other</option></select></label>{data.service==='Strategic talent partnership'?<p className="text-sm text-slate-600">For a longer-term partnership, you can also <Link href="/partner" className="font-semibold text-[#0b4ee8] underline-offset-4 hover:underline">apply on our partner page</Link>.</p>:null}<label className="block text-sm font-semibold">What are you trying to solve? *<textarea className={`${field} min-h-36 resize-y`} name="message" value={data.message} onChange={update} required placeholder="Tell us about the role, market, timeline and what has made the search difficult."/></label><div className="flex flex-col gap-4 border-t border-[#e2ecf8] pt-6 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs text-slate-500"><Check className="h-4 w-4 text-[#08a9a4]"/>Your information is handled confidentially.</p><button disabled={loading} className="button-primary disabled:opacity-60">{loading?<><Loader2 className="h-4 w-4 animate-spin"/>Sending</>:<>Send your brief <Send className="h-4 w-4"/></>}</button></div></form></div>
  </div></section>
  <section className="bg-[#f2f8ff] py-20"><div className="section-shell flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow">Exploring the market?</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">See where our networks run deepest.</h2></div><Link href="/areas" className="button-primary">Explore locations <ArrowRight className="h-4 w-4"/></Link></div></section><Footer/></main>
}
