import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, ChevronRight, MapPin } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import StructuredData from '@/components/StructuredData';
import { countryInfo, getLocations } from '@/lib/locations';

type Props={params:{country:string}}; const valid=(v:string):v is keyof typeof countryInfo=>v in countryInfo;
export function generateStaticParams(){return Object.keys(countryInfo).map(country=>({country}))}
export function generateMetadata({params}:Props):Metadata{if(!valid(params.country))return{};const info=countryInfo[params.country];return{title:`${info.name} Energy & Engineering Recruitment`,description:`Specialist energy, engineering, infrastructure and data-centre recruitment across ${info.name}. Explore Rectify's key local talent markets.`,alternates:{canonical:`/areas/${params.country}`}}}

export default function CountryPage({params}:Props){if(!valid(params.country))notFound();const info=countryInfo[params.country],places=getLocations(params.country),isGermany=params.country==='germany';return <main className="overflow-hidden bg-white text-[#03104b]"><Navigation activePage="areas"/>
 <section className="watercolor relative pb-24 pt-36 lg:pt-44"><div className="brand-grid absolute inset-0 opacity-35"/><div className="section-shell relative"><nav className="flex items-center gap-2 text-sm text-slate-500"><Link href="/areas">Locations</Link><ChevronRight className="h-4 w-4"/><span className="font-semibold text-[#03104b]">{info.name}</span></nav><div className="mt-14 grid gap-10 lg:grid-cols-[1fr_.35fr] lg:items-end"><div><p className="eyebrow">{info.label}</p><h1 className="mt-7 text-6xl font-semibold leading-[.94] tracking-[-.06em] sm:text-8xl">Talent across <span className="display-serif text-[#0b4ee8]">{info.name}.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600">{info.summary}</p></div><div className="brand-card bg-white/70 p-7 backdrop-blur"><p className="text-6xl font-semibold tracking-tight">{places.length}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#0b4ee8]">key markets covered</p></div></div></div></section>
 <section className="section-shell py-24 lg:py-32"><div className="mb-12 grid gap-6 lg:grid-cols-2"><div><p className="eyebrow">Local talent markets</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.05em]">{isGermany?'Germany, market by market.':'The United States, market by market.'}</h2></div><p className="max-w-xl self-end leading-7 text-slate-600">Explore hiring context, in-demand disciplines and the specialist talent we help organisations secure in each area.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{places.map((place,index)=><Link key={place.slug} href={`/areas/${params.country}/${place.slug}`} className={`group relative min-h-[280px] overflow-hidden rounded-3xl border p-7 transition duration-300 hover:-translate-y-1 hover:shadow-xl ${index===0?'border-blue-200 bg-[#e5edf9]':'border-slate-200 bg-white'}`}><span className="font-mono text-[10px] text-slate-400">/{String(index+1).padStart(2,'0')}</span><MapPin className="absolute right-7 top-7 h-5 w-5 text-blue-700"/><div className="absolute bottom-7 left-7 right-7"><h3 className="text-3xl font-semibold tracking-tight">{place.name}</h3><p className="mt-1 text-sm text-slate-500">{place.region}</p><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{place.intro}</p><ArrowRight className="mt-5 h-4 w-4 text-blue-700 transition group-hover:translate-x-1"/></div></Link>)}</div></section>
 <section className="relative overflow-hidden bg-[#06165b] py-20 text-white"><div className="brand-grid absolute inset-0 opacity-20"/><div className="section-shell relative flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow !text-[#42e5dd]">Market intelligence first</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Planning your next hire?</h2></div><Link href="/contact" className="button-light">Talk to a specialist <ArrowRight className="h-4 w-4"/></Link></div></section><Footer/><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:`${info.name} specialist recruitment`,provider:{'@type':'Organization',name:'Rectify International'},areaServed:info.name}}/></main>}
