import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Check, ChevronRight, MapPin } from 'lucide-react';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import StructuredData from '@/components/StructuredData';
import { countryInfo, locations } from '@/lib/locations';

type Props={params:{country:string;location:string}};const find=(country:string,slug:string)=>locations.find(x=>x.country===country&&x.slug===slug);
export function generateStaticParams(){return locations.map(({country,slug})=>({country,location:slug}))}
export function generateMetadata({params}:Props):Metadata{const p=find(params.country,params.location);if(!p)return{};const country=countryInfo[p.country].name;return{title:`${p.name} Energy & Engineering Recruitment`,description:`Specialist energy, engineering, infrastructure and data-centre recruitment in ${p.name}, ${country}. Local talent intelligence and targeted search from Rectify.`,alternates:{canonical:`/areas/${p.country}/${p.slug}`}}}

export default function LocationPage({params}:Props){const place=find(params.country,params.location);if(!place)notFound();const country=countryInfo[place.country],nearby=locations.filter(x=>x.country===place.country&&x.slug!==place.slug).slice(0,6);return <main className="overflow-hidden bg-white text-[#03104b]"><Navigation activePage="areas"/>
 <section className="watercolor relative pb-24 pt-36 lg:pt-44"><div className="brand-grid absolute inset-0 opacity-35"/><div className="section-shell relative"><nav className="flex flex-wrap items-center gap-2 text-sm text-slate-500"><Link href="/areas">Locations</Link><ChevronRight className="h-4 w-4"/><Link href={`/areas/${place.country}`}>{country.name}</Link><ChevronRight className="h-4 w-4"/><span className="font-semibold text-[#03104b]">{place.name}</span></nav><div className="mt-14 max-w-5xl"><div className="inline-flex items-center gap-2 rounded-full border border-[#b9ccec] bg-white/50 px-3 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#0b4ee8]"><MapPin className="h-3.5 w-3.5"/>{place.region}</div><h1 className="mt-7 text-6xl font-semibold leading-[.93] tracking-[-.06em] sm:text-8xl">Finding exceptional talent in <span className="display-serif text-[#0b4ee8]">{place.name}.</span></h1><p className="mt-8 max-w-3xl text-lg leading-8 text-slate-600">{place.intro}</p><Link href="/contact" className="button-primary mt-9">Discuss a search in {place.name}<ArrowRight className="h-4 w-4"/></Link></div></div></section>
 <section className="section-shell grid gap-12 py-24 lg:grid-cols-[1fr_.78fr] lg:py-32"><div><p className="eyebrow">Market focus</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.05em]">Where we add value in <span className="display-serif text-[#0b4ee8]">{place.name}.</span></h2><p className="mt-6 max-w-2xl leading-7 text-slate-600">We combine targeted headhunting with sector knowledge and live market feedback. The result is a more relevant shortlist, clearer expectations and fewer wasted conversations.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{place.strengths.map((item,i)=><div key={item} className="brand-card min-h-36 p-6"><span className="font-mono text-[10px] text-[#0b4ee8]">/0{i+1}</span><p className="mt-8 font-semibold">{item}</p></div>)}</div></div><aside className="relative overflow-hidden rounded-[2rem] bg-[#06165b] p-8 text-white sm:p-10"><div className="brand-grid absolute inset-0 opacity-20"/><div className="relative"><p className="eyebrow !text-[#42e5dd]">Roles we recruit</p><h2 className="mt-4 text-3xl font-semibold">Specialist and leadership talent</h2><ul className="mt-9 space-y-5">{place.roles.map(role=><li key={role} className="flex gap-3 border-b border-white/15 pb-5 text-blue-100/80"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#20ddd5]"><Check className="h-3 w-3 text-[#03104b]"/></span>{role}</li>)}</ul><Link href="/services" className="magnetic-link mt-7 !text-[#42e5dd]">Explore our expertise <ArrowRight className="h-4 w-4"/></Link></div></aside></section>
 <section className="bg-[#f2f8ff] py-24"><div className="section-shell"><div className="grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Our approach</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.05em]">A search process built for scarce skills.</h2></div><div className="space-y-5 text-slate-600"><p className="leading-7">We build a precise view of your technical requirement, project context and candidate proposition before approaching the market. We identify talent in {place.name}, across {country.name}, and internationally where relocation or remote delivery is viable.</p><p className="leading-7">Every assignment includes direct outreach, qualification and transparent feedback on compensation, availability and competitor demand.</p></div></div><div className="mt-14 grid gap-3 sm:grid-cols-3">{['Define the market','Engage the right people','Deliver a qualified shortlist'].map((step,i)=><div key={step} className="brand-card p-7"><span className="font-mono text-xs text-[#0b4ee8]">/0{i+1}</span><h3 className="mt-14 text-xl font-semibold">{step}</h3></div>)}</div></div></section>
 <section className="section-shell py-24"><h2 className="text-3xl font-semibold tracking-[-.03em]">Explore more {country.name} markets</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{nearby.map(item=><Link key={item.slug} href={`/areas/${item.country}/${item.slug}`} className="group flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 font-semibold transition hover:border-blue-300"><span>{item.name}</span><ArrowRight className="h-4 w-4 text-blue-700 transition group-hover:translate-x-1"/></Link>)}</div></section>
 <section className="relative overflow-hidden bg-[#06165b] py-20 text-white"><div className="brand-grid absolute inset-0 opacity-20"/><div className="section-shell relative flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow !text-[#42e5dd]">Open a search</p><h2 className="mt-4 text-4xl font-semibold">Hiring in {place.name}?</h2></div><Link href="/contact" className="button-light">Start a conversation <ArrowRight className="h-4 w-4"/></Link></div></section><Footer/><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:`Energy and engineering recruitment in ${place.name}`,description:place.intro,provider:{'@type':'Organization',name:'Rectify International'},areaServed:{'@type':'City',name:place.name}}}/></main>}
