export type Location = {
  country: 'united-states' | 'germany';
  slug: string;
  name: string;
  region: string;
  intro: string;
  strengths: string[];
  roles: string[];
};

export const countryInfo = {
  'united-states': {
    name: 'United States',
    label: 'Primary market',
    summary: 'Our primary market, spanning energy transition, power infrastructure, renewables, data centres and mission-critical engineering across the country’s key talent hubs.',
  },
  germany: {
    name: 'Germany',
    label: 'Secondary market',
    summary: 'Our core European market, spanning the Energiewende, grid modernisation, renewables, industrial decarbonisation and mission-critical infrastructure.',
  },
} as const;

export const locations: Location[] = [
  { country: 'united-states', slug: 'houston', name: 'Houston', region: 'Texas Gulf Coast', intro: 'Houston is the US energy capital, combining oil and gas transition, power generation, hydrogen, carbon management and large-scale engineering delivery.', strengths: ['Energy transition and power', 'Hydrogen and carbon management', 'Major project engineering'], roles: ['Project and engineering directors', 'Power systems engineers', 'Hydrogen and CCUS specialists', 'Commercial and development leaders'] },
  { country: 'united-states', slug: 'dallas', name: 'Dallas', region: 'North Texas', intro: 'Dallas is a major hub for data centres, power infrastructure, utilities and corporate energy functions serving the fast-growing Texas market.', strengths: ['Data centres and mission critical', 'Power and utilities', 'Corporate energy and infrastructure'], roles: ['Commissioning managers', 'MEP and electrical specialists', 'Utility professionals', 'Construction project leaders'] },
  { country: 'united-states', slug: 'austin', name: 'Austin', region: 'Central Texas', intro: 'Austin blends energy technology, climate software, advanced manufacturing and a fast-growing clean-tech ecosystem alongside Texas power and infrastructure demand.', strengths: ['Energy technology and software', 'Clean-tech ventures', 'Electrification and storage'], roles: ['Technical product leaders', 'Energy software specialists', 'Battery and storage professionals', 'Commercialisation talent'] },
  { country: 'united-states', slug: 'denver', name: 'Denver', region: 'Colorado / Mountain West', intro: 'Denver and the Mountain West are strong markets for wind, solar, storage, transmission and renewable project development across the interior US.', strengths: ['Onshore wind and solar', 'Transmission and storage', 'Renewable project development'], roles: ['Development managers', 'Grid connection specialists', 'Asset managers', 'Land and permitting professionals'] },
  { country: 'united-states', slug: 'phoenix', name: 'Phoenix', region: 'Arizona Southwest', intro: 'Phoenix combines large-scale solar, battery storage and one of America’s fastest-growing data-centre and semiconductor infrastructure markets.', strengths: ['Utility-scale solar and storage', 'Data centres', 'Semiconductor facilities'], roles: ['Solar project professionals', 'Facilities and power engineers', 'Commissioning specialists', 'Construction managers'] },
  { country: 'united-states', slug: 'chicago', name: 'Chicago', region: 'Midwest', intro: 'Chicago anchors Midwest utilities, grid modernisation, industrial decarbonisation and major infrastructure programmes across the Great Lakes region.', strengths: ['Utilities and power networks', 'Industrial decarbonisation', 'Infrastructure delivery'], roles: ['Power systems professionals', 'Programme managers', 'Process and mechanical engineers', 'Project controls specialists'] },
  { country: 'united-states', slug: 'atlanta', name: 'Atlanta', region: 'Southeast', intro: 'Atlanta is a leading Southeast hub for data centres, power delivery, logistics infrastructure and corporate energy functions.', strengths: ['Data centres and power', 'Logistics infrastructure', 'Corporate energy operations'], roles: ['Electrical and MEP engineers', 'Data-centre project leads', 'Utility professionals', 'Operations managers'] },
  { country: 'united-states', slug: 'new-york', name: 'New York', region: 'New York Metro', intro: 'New York is a centre for energy investment, offshore wind, grid resilience and executive leadership across infrastructure and climate markets.', strengths: ['Energy investment and finance', 'Offshore wind', 'Grid resilience and infrastructure'], roles: ['Investment and development leaders', 'Commercial directors', 'Sustainability professionals', 'Executive appointments'] },
  { country: 'united-states', slug: 'boston', name: 'Boston', region: 'New England', intro: 'Boston’s research and clean-tech ecosystem supports offshore wind, climate innovation, energy software and advanced engineering talent.', strengths: ['Offshore wind and clean tech', 'Energy software and deep tech', 'Research-led innovation'], roles: ['Offshore wind specialists', 'Software and data professionals', 'Innovation leaders', 'Technical programme managers'] },
  { country: 'united-states', slug: 'san-francisco', name: 'San Francisco Bay Area', region: 'Northern California', intro: 'The Bay Area is a global centre for climate technology, energy software, electrification and venture-backed infrastructure innovation.', strengths: ['Climate technology', 'Energy software', 'Electrification and mobility'], roles: ['Technical founders and leaders', 'Product and engineering managers', 'Climate tech specialists', 'Commercialisation professionals'] },
  { country: 'united-states', slug: 'northern-virginia', name: 'Northern Virginia', region: 'Washington DC Metro', intro: 'Northern Virginia is the world’s densest data-centre market, with intense demand for power, cooling, commissioning and mission-critical engineering talent.', strengths: ['Hyperscale data centres', 'Mission-critical power', 'Grid and interconnection'], roles: ['Commissioning managers', 'Electrical design specialists', 'Critical facilities engineers', 'Construction project leaders'] },
  { country: 'united-states', slug: 'charlotte', name: 'Charlotte', region: 'Carolinas', intro: 'Charlotte is a strong energy and utilities market, supporting power generation, grid investment and corporate energy headquarters across the Carolinas.', strengths: ['Utilities and power generation', 'Grid investment', 'Corporate energy functions'], roles: ['Utility professionals', 'Power engineers', 'Commercial energy leaders', 'Project managers'] },
  { country: 'united-states', slug: 'seattle', name: 'Seattle', region: 'Pacific Northwest', intro: 'Seattle combines hydropower heritage, data-centre growth, climate technology and advanced engineering across the Pacific Northwest.', strengths: ['Hydropower and renewables', 'Data centres', 'Climate and engineering technology'], roles: ['Power and civil engineers', 'Facilities specialists', 'Software and systems talent', 'Project directors'] },
  { country: 'united-states', slug: 'los-angeles', name: 'Los Angeles', region: 'Southern California', intro: 'Los Angeles supports energy transition, port and transport infrastructure, utility programmes and large-scale built-environment delivery across Southern California.', strengths: ['Energy transition programmes', 'Ports and transport infrastructure', 'Utilities and built environment'], roles: ['Programme and project directors', 'Civil and structural engineers', 'Sustainability specialists', 'Commercial managers'] },
  { country: 'germany', slug: 'berlin', name: 'Berlin', region: 'Berlin-Brandenburg', intro: 'Berlin combines climate technology, energy software, infrastructure investment and a fast-growing clean-tech ecosystem, with Brandenburg adding major solar, wind and battery projects.', strengths: ['Climate technology and energy software', 'Solar, storage and grid innovation', 'Public infrastructure and mobility'], roles: ['Country and commercial leaders', 'Grid and power systems engineers', 'Project development specialists', 'Software and data professionals'] },
  { country: 'germany', slug: 'hamburg', name: 'Hamburg', region: 'Northern Germany', intro: 'Hamburg is a leading centre for onshore and offshore wind, maritime infrastructure, green hydrogen and major-project delivery across northern Germany.', strengths: ['Onshore and offshore wind', 'Hydrogen and maritime decarbonisation', 'Ports and heavy infrastructure'], roles: ['Offshore project managers', 'Wind engineers and package leads', 'Hydrogen development professionals', 'Construction and commercial managers'] },
  { country: 'germany', slug: 'munich', name: 'Munich', region: 'Bavaria', intro: 'Munich and the wider Bavarian market bring together advanced engineering, mobility, energy technology, data centres and high-growth climate ventures.', strengths: ['Advanced engineering and automation', 'Energy technology and mobility', 'Data centres and mission critical'], roles: ['Electrical and mechanical engineers', 'Automation and controls specialists', 'Programme and project directors', 'Technical sales leaders'] },
  { country: 'germany', slug: 'frankfurt', name: 'Frankfurt', region: 'Hesse / Rhine-Main', intro: 'Frankfurt is Germany’s principal data-centre market and a major hub for finance, investment and power-intensive digital infrastructure.', strengths: ['Data centres and mission critical', 'Power and grid connections', 'Infrastructure investment'], roles: ['Commissioning managers', 'MEP and electrical specialists', 'Development and investment professionals', 'Construction project leaders'] },
  { country: 'germany', slug: 'cologne', name: 'Cologne', region: 'North Rhine-Westphalia', intro: 'Cologne sits within one of Europe’s densest industrial and infrastructure corridors, supporting utilities, engineering consultancies and the low-carbon transformation of the Rhine region.', strengths: ['Utilities and power networks', 'Industrial decarbonisation', 'Engineering and project consultancy'], roles: ['Power systems professionals', 'Civil and structural engineers', 'Sustainability specialists', 'Project controls professionals'] },
  { country: 'germany', slug: 'dusseldorf', name: 'Düsseldorf', region: 'North Rhine-Westphalia', intro: 'Düsseldorf is a commercial centre for energy, utilities and infrastructure businesses operating across Germany’s largest industrial state.', strengths: ['Energy trading and utilities', 'Grid and infrastructure programmes', 'Corporate energy transition'], roles: ['Commercial and origination leaders', 'Grid connection specialists', 'Programme managers', 'Energy transition consultants'] },
  { country: 'germany', slug: 'stuttgart', name: 'Stuttgart', region: 'Baden-Württemberg', intro: 'Stuttgart’s engineering heritage is evolving rapidly through electrification, automation, smart manufacturing and sustainable built-environment programmes.', strengths: ['Automation and controls', 'Electrification and mobility', 'Advanced manufacturing infrastructure'], roles: ['Controls and automation engineers', 'Electrical design specialists', 'Construction managers', 'Engineering leadership'] },
  { country: 'germany', slug: 'leipzig', name: 'Leipzig', region: 'Saxony / Central Germany', intro: 'Leipzig is an expanding logistics, energy and advanced-manufacturing centre with strong links to regional renewables and grid investment.', strengths: ['Solar and onshore wind', 'Grid and utility infrastructure', 'Advanced manufacturing'], roles: ['Renewable project developers', 'Grid engineers', 'Site and construction managers', 'Operations professionals'] },
  { country: 'germany', slug: 'dresden', name: 'Dresden', region: 'Saxony', intro: 'Dresden combines semiconductor and advanced-technology investment with growing requirements for resilient power, specialist facilities and sustainable infrastructure.', strengths: ['High-tech and semiconductor facilities', 'Mission-critical power', 'Engineering and construction'], roles: ['Facilities engineers', 'Electrical and mechanical leads', 'Commissioning specialists', 'Capital-project managers'] },
  { country: 'germany', slug: 'hanover', name: 'Hanover', region: 'Lower Saxony', intro: 'Hanover is well placed for onshore wind, grid infrastructure, industrial technology and large-scale development across Lower Saxony.', strengths: ['Onshore wind and storage', 'Transmission and distribution', 'Industrial technology'], roles: ['Wind development managers', 'High-voltage engineers', 'Land and permitting specialists', 'Asset managers'] },
  { country: 'germany', slug: 'bremen', name: 'Bremen', region: 'Northwest Germany', intro: 'Bremen’s maritime and aerospace engineering base supports offshore wind, ports, hydrogen and complex infrastructure delivery across the northwest.', strengths: ['Offshore wind supply chain', 'Ports and maritime infrastructure', 'Green hydrogen'], roles: ['Marine and structural engineers', 'Package and interface managers', 'HSE and quality professionals', 'Hydrogen project specialists'] },
  { country: 'germany', slug: 'nuremberg', name: 'Nuremberg', region: 'Franconia / Bavaria', intro: 'Nuremberg and the wider Franconian region offer a strong base in power electronics, automation, energy systems and industrial engineering.', strengths: ['Power electronics and electrification', 'Automation and controls', 'Industrial energy systems'], roles: ['Power electronics engineers', 'Controls specialists', 'Technical project managers', 'Product and engineering leaders'] },
  { country: 'germany', slug: 'ruhr-area', name: 'Ruhr Area', region: 'North Rhine-Westphalia', intro: 'The Ruhr is at the centre of Germany’s industrial transition, where legacy energy and heavy industry meet hydrogen, grid renewal and large-scale decarbonisation.', strengths: ['Industrial decarbonisation', 'Hydrogen and energy networks', 'Major capital programmes'], roles: ['Decarbonisation programme leads', 'Process and mechanical engineers', 'Project controls leaders', 'Energy infrastructure specialists'] },
  { country: 'germany', slug: 'karlsruhe', name: 'Karlsruhe', region: 'Baden-Württemberg', intro: 'Karlsruhe blends energy research, digital technology, utilities and engineering, making it a strong talent market for smart grids and energy systems.', strengths: ['Smart grids and energy software', 'Utilities and power engineering', 'Research-led technology'], roles: ['Energy software specialists', 'Grid planning engineers', 'Data and optimisation professionals', 'Technical product managers'] },
  { country: 'germany', slug: 'freiburg', name: 'Freiburg', region: 'Southwest Germany', intro: 'Freiburg is recognised for solar energy, sustainable construction and environmental research, with a mature community focused on the low-carbon economy.', strengths: ['Solar and distributed energy', 'Sustainable buildings', 'Environmental technology'], roles: ['Solar project professionals', 'Sustainability consultants', 'Building-services engineers', 'Research and innovation leaders'] },
  { country: 'germany', slug: 'rostock', name: 'Rostock', region: 'Mecklenburg-Vorpommern', intro: 'Rostock is strategically positioned for Baltic offshore wind, port infrastructure, maritime engineering and emerging hydrogen supply chains.', strengths: ['Baltic offshore wind', 'Port and maritime projects', 'Hydrogen infrastructure'], roles: ['Offshore construction specialists', 'Marine coordinators', 'Electrical package managers', 'Port infrastructure professionals'] },
];

export const getLocations = (country: Location['country']) => locations.filter((location) => location.country === country);
