export type Location = {
  country: 'germany' | 'united-kingdom';
  slug: string;
  name: string;
  region: string;
  intro: string;
  strengths: string[];
  roles: string[];
};

export const countryInfo = {
  germany: {
    name: 'Germany',
    label: 'Primary market',
    summary: 'Our core European market, spanning the Energiewende, grid modernisation, renewables, industrial decarbonisation and mission-critical infrastructure.',
  },
  'united-kingdom': {
    name: 'United Kingdom',
    label: 'Specialist market',
    summary: 'Specialist search support across the UK’s energy transition, infrastructure, engineering and data-centre ecosystems.',
  },
} as const;

export const locations: Location[] = [
  { country: 'germany', slug: 'berlin', name: 'Berlin', region: 'Berlin-Brandenburg', intro: 'Berlin combines climate technology, energy software, infrastructure investment and a fast-growing clean-tech ecosystem, with Brandenburg adding major solar, wind and battery projects.', strengths: ['Climate technology and energy software', 'Solar, storage and grid innovation', 'Public infrastructure and mobility'], roles: ['Country and commercial leaders', 'Grid and power systems engineers', 'Project development specialists', 'Software and data professionals'] },
  { country: 'germany', slug: 'hamburg', name: 'Hamburg', region: 'Northern Germany', intro: 'Hamburg is a leading centre for onshore and offshore wind, maritime infrastructure, green hydrogen and major-project delivery across northern Germany.', strengths: ['Onshore and offshore wind', 'Hydrogen and maritime decarbonisation', 'Ports and heavy infrastructure'], roles: ['Offshore project managers', 'Wind engineers and package leads', 'Hydrogen development professionals', 'Construction and commercial managers'] },
  { country: 'germany', slug: 'munich', name: 'Munich', region: 'Bavaria', intro: 'Munich and the wider Bavarian market bring together advanced engineering, mobility, energy technology, data centres and high-growth climate ventures.', strengths: ['Advanced engineering and automation', 'Energy technology and mobility', 'Data centres and mission critical'], roles: ['Electrical and mechanical engineers', 'Automation and controls specialists', 'Programme and project directors', 'Technical sales leaders'] },
  { country: 'germany', slug: 'frankfurt', name: 'Frankfurt', region: 'Hesse / Rhine-Main', intro: 'Frankfurt is Germany’s principal data-centre market and a major hub for finance, investment and power-intensive digital infrastructure.', strengths: ['Data centres and mission critical', 'Power and grid connections', 'Infrastructure investment'], roles: ['Commissioning managers', 'MEP and electrical specialists', 'Development and investment professionals', 'Construction project leaders'] },
  { country: 'germany', slug: 'cologne', name: 'Cologne', region: 'North Rhine-Westphalia', intro: 'Cologne sits within one of Europe’s densest industrial and infrastructure corridors, supporting utilities, engineering consultancies and the low-carbon transformation of the Rhine region.', strengths: ['Utilities and power networks', 'Industrial decarbonisation', 'Engineering and project consultancy'], roles: ['Power systems professionals', 'Civil and structural engineers', 'Sustainability specialists', 'Project controls professionals'] },
  { country: 'germany', slug: 'dusseldorf', name: 'Düsseldorf', region: 'North Rhine-Westphalia', intro: 'Düsseldorf is a commercial centre for energy, utilities and infrastructure businesses operating across Germany’s largest industrial state.', strengths: ['Energy trading and utilities', 'Grid and infrastructure programmes', 'Corporate energy transition'], roles: ['Commercial and origination leaders', 'Grid connection specialists', 'Programme managers', 'Energy transition consultants'] },
  { country: 'germany', slug: 'stuttgart', name: 'Stuttgart', region: 'Baden-Württemberg', intro: 'Stuttgart’s engineering heritage is evolving rapidly through electrification, automation, smart manufacturing and sustainable built-environment programmes.', strengths: ['Automation and controls', 'Electrification and mobility', 'Advanced manufacturing infrastructure'], roles: ['Controls and automation engineers', 'Electrical design specialists', 'Construction managers', 'Engineering leadership'] },
  { country: 'germany', slug: 'leipzig', name: 'Leipzig', region: 'Saxony / Central Germany', intro: 'Leipzig is an expanding logistics, energy and advanced-manufacturing centre with strong links to regional renewables and grid investment.', strengths: ['Solar and onshore wind', 'Grid and utility infrastructure', 'Advanced manufacturing'], roles: ['Renewable project developers', 'Grid engineers', 'Site and construction managers', 'Operations professionals'] },
  { country: 'germany', slug: 'dresden', name: 'Dresden', region: 'Saxony', intro: 'Dresden combines semiconductor and advanced-technology investment with growing requirements for resilient power, specialist facilities and sustainable infrastructure.', strengths: ['High-tech and semiconductor facilities', 'Mission-critical power', 'Engineering and construction'], roles: ['Facilities engineers', 'Electrical and mechanical leads', 'Commissioning specialists', 'Capital-project managers'] },
  { country: 'germany', slug: 'hanover', name: 'Hanover', region: 'Lower Saxony', intro: 'Hanover is well placed for onshore wind, grid infrastructure, industrial technology and large-scale development across Lower Saxony.', strengths: ['Onshore wind and storage', 'Transmission and distribution', 'Industrial technology'], roles: ['Wind development managers', 'High-voltage engineers', 'Land and permitting specialists', 'Asset managers'] },
  { country: 'germany', slug: 'bremen', name: 'Bremen', region: 'Northwest Germany', intro: 'Bremen’s maritime and aerospace engineering base supports offshore wind, ports, hydrogen and complex infrastructure delivery across the northwest.', strengths: ['Offshore wind supply chain', 'Ports and maritime infrastructure', 'Green hydrogen'], roles: ['Marine and structural engineers', 'Package and interface managers', 'HSE and quality professionals', 'Hydrogen project specialists'] },
  { country: 'germany', slug: 'nuremberg', name: 'Nuremberg', region: 'Franconia / Bavaria', intro: 'Nuremberg and the wider Franconian region offer a strong base in power electronics, automation, energy systems and industrial engineering.', strengths: ['Power electronics and electrification', 'Automation and controls', 'Industrial energy systems'], roles: ['Power electronics engineers', 'Controls specialists', 'Technical project managers', 'Product and engineering leaders'] },
  { country: 'germany', slug: 'ruhr-area', name: 'Ruhr Area', region: 'North Rhine-Westphalia', intro: 'The Ruhr is at the centre of Germany’s industrial transition, where legacy energy and heavy industry meet hydrogen, grid renewal and large-scale decarbonisation.', strengths: ['Industrial decarbonisation', 'Hydrogen and energy networks', 'Major capital programmes'], roles: ['Decarbonisation programme leads', 'Process and mechanical engineers', 'Project controls leaders', 'Energy infrastructure specialists'] },
  { country: 'germany', slug: 'karlsruhe', name: 'Karlsruhe', region: 'Baden-Württemberg', intro: 'Karlsruhe blends energy research, digital technology, utilities and engineering, making it a strong talent market for smart grids and energy systems.', strengths: ['Smart grids and energy software', 'Utilities and power engineering', 'Research-led technology'], roles: ['Energy software specialists', 'Grid planning engineers', 'Data and optimisation professionals', 'Technical product managers'] },
  { country: 'germany', slug: 'freiburg', name: 'Freiburg', region: 'Southwest Germany', intro: 'Freiburg is recognised for solar energy, sustainable construction and environmental research, with a mature community focused on the low-carbon economy.', strengths: ['Solar and distributed energy', 'Sustainable buildings', 'Environmental technology'], roles: ['Solar project professionals', 'Sustainability consultants', 'Building-services engineers', 'Research and innovation leaders'] },
  { country: 'germany', slug: 'rostock', name: 'Rostock', region: 'Mecklenburg-Vorpommern', intro: 'Rostock is strategically positioned for Baltic offshore wind, port infrastructure, maritime engineering and emerging hydrogen supply chains.', strengths: ['Baltic offshore wind', 'Port and maritime projects', 'Hydrogen infrastructure'], roles: ['Offshore construction specialists', 'Marine coordinators', 'Electrical package managers', 'Port infrastructure professionals'] },
  { country: 'united-kingdom', slug: 'london', name: 'London', region: 'London and the South East', intro: 'London is a global centre for energy investment, infrastructure development, climate technology and executive leadership.', strengths: ['Energy investment and development', 'Climate technology', 'Corporate and executive functions'], roles: ['Investment and development leaders', 'Commercial directors', 'Sustainability professionals', 'Executive appointments'] },
  { country: 'united-kingdom', slug: 'manchester', name: 'Manchester', region: 'North West England', intro: 'Manchester supports a broad base of engineering, utilities, digital infrastructure and net-zero programmes across the North West.', strengths: ['Engineering and utilities', 'Data centres', 'Regional infrastructure'], roles: ['Engineering managers', 'Project and programme professionals', 'MEP specialists', 'Utility professionals'] },
  { country: 'united-kingdom', slug: 'birmingham', name: 'Birmingham', region: 'West Midlands', intro: 'Birmingham is central to UK transport, construction, power and regeneration programmes, with access to deep engineering talent.', strengths: ['Transport and major projects', 'Built environment', 'Power infrastructure'], roles: ['Project directors', 'Civil and structural engineers', 'Commercial managers', 'Power engineers'] },
  { country: 'united-kingdom', slug: 'bristol', name: 'Bristol', region: 'South West England', intro: 'Bristol is a strong market for offshore wind, environmental engineering, technology and sustainable infrastructure across the South West.', strengths: ['Offshore wind', 'Environmental engineering', 'Clean technology'], roles: ['Renewable energy specialists', 'Environmental consultants', 'Engineering leads', 'Project developers'] },
  { country: 'united-kingdom', slug: 'edinburgh', name: 'Edinburgh', region: 'Scotland', intro: 'Edinburgh combines renewable-energy development and finance with access to Scotland’s onshore and offshore wind markets.', strengths: ['Renewable energy finance', 'Onshore and offshore wind', 'Grid and development'], roles: ['Development managers', 'Investment professionals', 'Grid specialists', 'Consenting professionals'] },
  { country: 'united-kingdom', slug: 'glasgow', name: 'Glasgow', region: 'Scotland', intro: 'Glasgow is a major engineering and infrastructure centre serving power networks, offshore energy and complex project delivery.', strengths: ['Power networks', 'Offshore engineering', 'Infrastructure delivery'], roles: ['Power systems engineers', 'Offshore engineers', 'Project controls specialists', 'Construction leaders'] },
  { country: 'united-kingdom', slug: 'leeds', name: 'Leeds', region: 'Yorkshire', intro: 'Leeds provides access to utilities, engineering consultancy, infrastructure and energy-transition talent across Yorkshire.', strengths: ['Utilities and infrastructure', 'Engineering consultancy', 'Regional development'], roles: ['Utility professionals', 'Design engineers', 'Programme managers', 'Commercial specialists'] },
  { country: 'united-kingdom', slug: 'cambridge', name: 'Cambridge', region: 'East of England', intro: 'Cambridge’s technology ecosystem is a source of energy software, deep-tech, sustainability and innovation leadership.', strengths: ['Climate and deep technology', 'Energy software', 'Research and innovation'], roles: ['Technical founders and leaders', 'Software and data specialists', 'Product managers', 'Innovation professionals'] },
  { country: 'united-kingdom', slug: 'oxford', name: 'Oxford', region: 'South East England', intro: 'Oxford supports a research-led cluster spanning battery technology, climate innovation, sustainable mobility and energy investment.', strengths: ['Battery and storage technology', 'Climate innovation', 'Sustainable mobility'], roles: ['Battery specialists', 'Research and engineering leaders', 'Commercialisation professionals', 'Technical programme managers'] },
  { country: 'united-kingdom', slug: 'reading', name: 'Reading', region: 'Thames Valley', intro: 'Reading and the Thames Valley are key locations for data centres, power infrastructure, engineering consultancies and technology businesses.', strengths: ['Data centres', 'Power and utilities', 'Technology infrastructure'], roles: ['Data-centre engineers', 'Commissioning professionals', 'Power specialists', 'Project managers'] },
];

export const getLocations = (country: Location['country']) => locations.filter((location) => location.country === country);
